apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: garnet-nodeport
  namespace: garnet
spec:
  ports:
  - port: 12306
    name: port2
    nodePort: 30800
    protocol: TCP
    targetPort: 12306
  selector:
    workload.user.cattle.io/workloadselector: deployment-garnet
  type: NodePort